target 'Test' do
  use_frameworks!

  pod 'Flutter', :podspec => './myID/Flutter.podspec'
  pod 'GoogleMLKit/FaceDetection', '~> 2'
  pod 'GoogleMLKit/TextRecognition', '~> 2'
  pod 'GoogleMLKit/BarcodeScanning', '~> 2'
end
